name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Configuration
          config_timezone: America/New_York
          config_padding: 5%
          
          # Base content
          base: header, activity, community, repositories, metadata
          
          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_colors: github
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 50
          plugin_habits_charts: yes
          
          plugin_followup: yes
          plugin_lines: yes
          
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 28
          plugin_people_size: 28
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_repositories: yes
